openapi: "3.0.0"
info:
  title: Simple API overview
  description: Griff desc
  version: 2.0.0
tags:
  - my tag
  - tagA
  - tagB
  - tagC
  - tagD
  - tagE
  - tagF
  - tagG
  - tagH
  - tagI
  - tagJ
  - tagK
  - tagL
  - tagM
  - tagN
  - tagO
  - tagP
  - tagQ
  - tagR
  - tagS
  - tagT
  - tagU
  - tagV
  - tagW
  - tagX
  - tagY
  - tagZ
  - tagA1
  - tagB1
  - tagC1
  - tagD1
  - tagE1
  - tagF1
  - tagG1
  - tagH1
  - tagI1
  - tagJ1
  - tagK1
  - tagL1
  - tagM1
  - tagN1
  - tagO1
  - tagP1
  - tagQ1
  - tagR1
  - tagS1
  - tagT1
  - tagU1
  - tagV1
  - tagW1
  - tagX1
  - tagY1
  - tagZ1
  - tagA2
  - tagB2
  - tagC2
  - tagD2
  - tagE2
  - tagF2
  - tagG2
  - tagH2
  - tagI2
  - tagJ2
  - tagK2
  - tagL2
  - tagM2
  - tagN2
  - tagO2
  - tagP2
  - tagQ2
  - tagR2
  - tagS2
  - tagT2
  - tagU2
  - tagV2
  - tagW2
  - tagX2
  - tagY2
  - tagZ2
  - tagA3
  - tagB3
  - tagC3
  - tagD3
  - tagE3
  - tagF3
  - tagG3
  - tagH3
  - tagI3
  - tagJ3
  - tagK3
  - tagL3
  - tagM3
  - tagN3
  - tagO3
  - tagP3
  - tagQ3
  - tagR3
  - tagS3
  - tagT3
  - tagU3
  - tagV3
  - tagW3
  - tagX3
  - tagY3
  - tagZ3
  - tagA4
  - tagB4
  - tagC4
  - tagD4
  - tagE4
  - tagF4
  - tagG4
  - tagH4
  - tagI4
  - tagJ4
  - tagK4
  - tagL4
  - tagM4
  - tagN4
  - tagO4
  - tagP4
  - tagQ4
  - tagR4
  - tagS4
  - tagT4
  - tagU4
  - tagV4
  - tagW4
  - tagX4
  - tagY4
  - tagZ4
  - tagA5
  - tagB5
  - tagC5
  - tagD5
  - tagE5
  - tagF5
  - tagG5
  - tagH5
  - tagI5
  - tagJ5
  - tagK5
  - tagL5
  - tagM5
  - tagN5
  - tagO5
  - tagP5
  - tagQ5
  - tagR5
  - tagS5
  - tagT5
  - tagU5
  - tagV5
  - tagW5
  - tagX5
  - tagY5
  - tagZ5
  - tagA6
  - tagB6
  - tagC6
  - tagD6
  - tagE6
  - tagF6
  - tagG6
  - tagH6
  - tagI6
  - tagJ6
  - tagK6
  - tagL6
  - tagM6
  - tagN6
  - tagO6
  - tagP6
  - tagQ6
  - tagR6
  - tagS6
  - tagT6
  - tagU6
  - tagV6
  - tagW6
  - tagX6
  - tagY6
  - tagZ6
  - tagA7
  - tagB7
  - tagC7
  - tagD7
  - tagE7
  - tagF7
  - tagG7
  - tagH7
  - tagI7
  - tagJ7
  - tagK7
  - tagL7
  - tagM7
  - tagN7
  - tagO7
  - tagP7
  - tagQ7
  - tagR7
  - tagS7
  - tagT7
  - tagU7
  - tagV7
  - tagW7
  - tagX7
  - tagY7
  - tagZ7
paths:
  /:
    get:
      operationId: listVersionsv2
      summary: List API versions
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples: 
                foo:
                  value: {
                    "versions": [
                        {
                            "status": "CURRENT",
                            "updated": "2011-01-21T11:33:21Z",
                            "id": "v2.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v2/",
                                    "rel": "self"
                                }
                            ]
                        },
                        {
                            "status": "EXPERIMENTAL",
                            "updated": "2013-07-23T11:33:21Z",
                            "id": "v3.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v3/",
                                    "rel": "self"
                                }
                            ]
                        }
                    ]
                 }
        '300':
          description: |-
            300 response
          content:
            application/json: 
              examples: 
                foo:
                  value: |
                   {
                    "versions": [
                          {
                            "status": "CURRENT",
                            "updated": "2011-01-21T11:33:21Z",
                            "id": "v2.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v2/",
                                    "rel": "self"
                                }
                            ]
                        },
                        {
                            "status": "EXPERIMENTAL",
                            "updated": "2013-07-23T11:33:21Z",
                            "id": "v3.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v3/",
                                    "rel": "self"
                                }
                            ]
                        }
                    ]
                   }
  /v2:
    get:
      operationId: getVersionDetailsv2
      summary: Show API version details
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json: 
              examples:
                foo:
                  value: {
                    "version": {
                      "status": "CURRENT",
                      "updated": "2011-01-21T11:33:21Z",
                      "media-types": [
                          {
                              "base": "application/xml",
                              "type": "application/vnd.openstack.compute+xml;version=2"
                          },
                          {
                              "base": "application/json",
                              "type": "application/vnd.openstack.compute+json;version=2"
                          }
                      ],
                      "id": "v2.0",
                      "links": [
                          {
                              "href": "http://127.0.0.1:8774/v2/",
                              "rel": "self"
                          },
                          {
                              "href": "http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf",
                              "type": "application/pdf",
                              "rel": "describedby"
                          },
                          {
                              "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                              "type": "application/vnd.sun.wadl+xml",
                              "rel": "describedby"
                          },
                          {
                            "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                            "type": "application/vnd.sun.wadl+xml",
                            "rel": "describedby"
                          }
                      ]
                    }
                  }
        '203':
          description: |-
            203 response
          content:
            application/json: 
              examples:
                foo:
                  value: {
                    "version": {
                      "status": "CURRENT",
                      "updated": "2011-01-21T11:33:21Z",
                      "media-types": [
                          {
                              "base": "application/xml",
                              "type": "application/vnd.openstack.compute+xml;version=2"
                          },
                          {
                              "base": "application/json",
                              "type": "application/vnd.openstack.compute+json;version=2"
                          }
                      ],
                      "id": "v2.0",
                      "links": [
                          {
                              "href": "http://23.253.228.211:8774/v2/",
                              "rel": "self"
                          },
                          {
                              "href": "http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf",
                              "type": "application/pdf",
                              "rel": "describedby"
                          },
                          {
                              "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                              "type": "application/vnd.sun.wadl+xml",
                              "rel": "describedby"
                          }
                      ]
                    }
                  }
